### ISSUE TITLE
Endpoint of SPOTIFY_REDIRECT_URI

### ISSUE THREAD

**Issue by KaliSky42** [anton-g/quizify#6]
Hi,
I can't figure out what is the endpoint of SPOTIFY_REDIRECT_URI in `template.env` / `development.env`.
Can you please improve your documentation, or give an exemple in `template.env`?
Regards

**Comment by anton-g** [comment]
Hi!

It should be something akin to `http://localhost:3000/auth/callback`.
I've updated the `template.env` with an example.

Thanks for the feedback!
